"""email column to studio_members table

Revision ID: a9dc75883c69
Revises: 
Create Date: 2020-05-07 23:26:01.911265

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a9dc75883c69'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('studio_member_roles', 'role_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    op.alter_column('studio_member_roles', 'studio_member_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    op.add_column('studio_members', sa.Column('email', sa.Text(), nullable=True))
    op.create_unique_constraint(None, 'studio_members', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'studio_members', type_='unique')
    op.drop_column('studio_members', 'email')
    op.alter_column('studio_member_roles', 'studio_member_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.alter_column('studio_member_roles', 'role_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    # ### end Alembic commands ###
