"""empty message

Revision ID: c2acbe6a798d
Revises: 410ec87948d9
Create Date: 2020-07-08 21:46:32.578185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2acbe6a798d'
down_revision = '410ec87948d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('studio_members', sa.Column('avatar', sa.Text(), nullable=True))
    op.alter_column('studio_members', 'email',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_constraint('studio_members_email_key', 'studio_members', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('studio_members_email_key', 'studio_members', ['email'])
    op.alter_column('studio_members', 'email',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('studio_members', 'avatar')
    # ### end Alembic commands ###
